# Site settings
title: Hendrix's Lab
email: sankalp.sans@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Somewhere I will host my teeny-tiny projects and experiences dealing with technology. 
  Speaking a lot about tech publically tends to  give me impostor syndromme. So I don't really do that.
  If you're really interested, Visit https://sankalpinspiration.wordpress.com
  for predominantly non-tech thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sankalpsans.github.io" # the base hostname & protocol for your site
twitter_username: sankalp_sans
github_username:  sankalpsans

# Build settings
markdown: kramdown
